# illa-builder 

version: "3.9"

services:
  illa-builder:
    container_name: illa-builder
    restart: always
    image: "illasoft/illa-builder:latest"
    environment:
    - GIN_MODE=release
    - PGDATA=/var/lib/postgresql/data/pgdata 
    ports:
      - "80:80"
    volumes:
      - illa_database:/var/lib/postgresql/data:rw
      - illa_drive:/opt/illa/drive:rw

volumes:
  illa_database:
  illa_drive:
