---
# illa-builder deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: illa-builder
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: illa-builder
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: illa-builder
        infrastructure: fargate
    spec:
      containers:
      - image: docker.io/illasoft/illa-builder:latest
        imagePullPolicy: Always
        name: illa-builder
        ports:
        - containerPort: 2022
        env:
        - name: ILLA_DEPLOY_MODE
          value: "self-host"
---
# illa-builder service
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: illa-builder
spec:
  ports:
    - port: 2022
      targetPort: 2022
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: illa-builder
    infrastructure: fargate
